# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationalForeignModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field_m2m', models.ManyToManyField(to='base_app.SimpleBaseTwo')),
                ('test_field_m2m_db_table', models.ManyToManyField(db_table='test_foreign_relational', to='base_app.SimpleBaseFour')),
                ('test_field_m2m_through', models.ManyToManyField(through='base_app.SimpleBaseThrough', to='base_app.SimpleBaseThree')),
            ],
        ),
        migrations.CreateModel(
            name='RelationalForeignModelMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field_m2m', models.ManyToManyField(to='base_app.SimpleBaseTwo')),
                ('test_field_m2m_db_table', models.ManyToManyField(db_table='test_mm_foreign_relational_meta', to='base_app.SimpleBaseFour')),
                ('test_field_m2m_through', models.ManyToManyField(through='base_app.SimpleBaseThroughMeta', to='base_app.SimpleBaseThree')),
            ],
            options={
                'db_table': 'test_foreign_relational_meta',
            },
        ),
        migrations.CreateModel(
            name='SimpleForeignFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(default='test_foreign_five', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleForeignFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(default='test_foreign_four', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleForeignOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(default='test_foreign_one', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleForeignThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(default='test_foreign_three', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleForeignThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.RelationalBaseModel')),
                ('test_field_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreign_app.SimpleForeignFive')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleForeignThroughMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.RelationalBaseModelMeta')),
                ('test_field_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreign_app.SimpleForeignFive')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleForeignTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(default='test_foreign_two', max_length=4)),
            ],
        ),
    ]
