# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('target_app', '0001_initial'),
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFKModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.TestModel')),
                ('test_second_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='target_app.SecondTestModel')),
            ],
        ),
        migrations.CreateModel(
            name='TestM2MModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_m2m', models.ManyToManyField(to='base_app.TestModel')),
                ('test_second_m2m', models.ManyToManyField(to='target_app.SecondTestModel')),
            ],
        ),
        migrations.CreateModel(
            name='TestO2OModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_o2o', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.TestModel')),
                ('test_second_o2o', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='target_app.SecondTestModel')),
            ],
        ),
    ]
