# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelationalBaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RelationalBaseModelMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'test_base_relational_meta',
            },
        ),
        migrations.CreateModel(
            name='SimpleBaseFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(default='test_base_four', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleBaseMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(default='test_base_meta', max_length=4)),
            ],
            options={
                'db_table': 'test_base_meta',
            },
        ),
        migrations.CreateModel(
            name='SimpleBaseOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(default='test_base_one', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleBaseThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(default='test_base_three', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleBaseThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleBaseThroughMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.SimpleBaseThree')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleBaseTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(default='test_base_two', max_length=4)),
            ],
        ),
    ]
